---
sidebar: sidebar 
permalink: reference_limitations_aws_991.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: これらの既知の制限は、 Amazon Web Services の Cloud Volumes ONTAP に固有のものです。 
---
= AWS での Cloud Volumes ONTAP 9.9.1 の既知の制限事項
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下に記載する制限は、 Amazon Web Services の Cloud Volumes ONTAP に固有のものです。また、必ず確認してください link:reference_limitations_991.html["すべてのクラウドプロバイダでの Cloud Volumes ONTAP 9.9.1 の制限事項"]。



== AWS Outpost の制限事項

AWS Outpost を使用している場合は、 Working Environment ウィザードで Outpost VPC を選択して、その Outpost に Cloud Volumes ONTAP を導入できます。エクスペリエンスは、 AWS に存在する他の VPC と同じです。最初に、 AWS Outpost にコネクタを導入する必要があります。

指摘すべき制限事項はいくつかあります。

* でサポートされるのはシングルノードの Cloud Volumes ONTAP システムのみです 今回は
* Cloud Volumes で使用できる EC2 インスタンス ONTAP は、 Outpost で利用できる機能に限定されています
* 現時点では、汎用 SSD （ gp2 ）のみがサポートされます




== Flash Cache の制限事項

C5D および R5D インスタンスタイプには、 Cloud Volumes ONTAP が _Flash Cache _ として使用するローカル NVMe ストレージが含まれます。次の制限事項に注意してください。

* Flash Cache のパフォーマンス向上を利用するには、すべてのボリュームで圧縮を無効にする必要があります。
+
Cloud Manager からボリュームを作成するときに Storage Efficiency を使用しないようにするか、またはボリュームを作成してから実行することができます http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["CLI を使用してデータ圧縮を無効にします"^]。

* 再起動後のキャッシュの再ウォームアップは、 Cloud Volumes ONTAP ではサポートされていません。




== Amazon CloudWatch から誤ったアラームが報告されます

Cloud Volumes ONTAP はアイドル時に CPU を解放しません https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] では、使用率が 100% になっていることが検出されたため、 EC2 インスタンスについて CPU 使用率の上昇を警告できます。このアラームは無視してかまいません。ONTAP statistics コマンドを実行すると、 CPU の実際の使用状況が表示されます。



== Cloud Volumes ONTAP HA ペアでは、ストレージの迅速な使用はサポートされません ギブバック

ノードがリブートしたら、ストレージを戻す前に、パートナーがデータを同期する必要があります。データの再同期にかかる時間は、ノードが停止している間にクライアントが書き込んだデータの量、およびギブバックの実行中のデータの書き込み速度によって異なります。

https://docs.netapp.com/us-en/occm/concept_ha.html#how-storage-works-in-an-ha-pair["Cloud Volumes ONTAP HA でのストレージの仕組みをご確認ください AWS で実行されているペア"^]。
