---
sidebar: sidebar 
permalink: reference_new_990.html 
keywords: what's new, new, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.9.0 には、いくつかの新機能と機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.9.0 の新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.9.0 には、いくつかの新機能と機能拡張が含まれています。

その他の機能と機能拡張は、 Cloud Manager の最新バージョンで導入されました。を参照してください https://docs.netapp.com/us-en/occm/reference_new_occm.html["Cloud Manager リリースノート"^] を参照してください。



== 最新のアップデート（ 2021 年 4 月 21 日）

AWS では、ディザスタリカバリ（ DR ）用に最大 24 個の Storage VM （ SVM ）を設定できるようになりました。これまでの制限は、 DR に使用する Storage VM 12 台でした。

link:reference_limits_aws_990.html#storage-vm-limits["Storage VM の制限に関する詳細情報"]。



== 最新のアップデート（ 2021 年 4 月 12 日）

Cloud Volumes ONTAP 9.9.0 のリリース以降、いくつかの更新が行われています。

* AWS アップデート *

* Cloud Volumes ONTAP では、 9.7 リリース以降、汎用 SSD （ GP3 ）ディスクがサポートされるようになりました。GP3 ディスクは、幅広いワークロードのコストとパフォーマンスのバランスが取れた、最も低コストの SSD です。
+
https://docs.netapp.com/us-en/occm/task_planning_your_config.html#sizing-your-system-in-aws["Cloud Volumes ONTAP で GP3 ディスクを使用する方法については、こちらをご覧ください"^]。

* Cloud Volumes ONTAP はコールド HDD （ sc1 ）ディスクをサポートしなくなりました。


これらの EBS ディスクの変更は、 Cloud Manager 3.2.5 の一部として導入されました。

* Azure アップデート *

* 新しい E シリーズ VM タイプがサポートされます。
+
** 4S_v3 でシングルノードシステムの場合は、 PAYGO Explore または BYOL を使用します
** ONTAP を使用する単一ノードシステムの場合は、 PAYGO Standard または BYOL を使用し、 HA ペアは PAYGO Premium または BYOL を使用します
** E64is_v3 ： PAYGO Premium または BYOL を使用したシングルノードシステム


* Cloud Volumes ONTAP BYOL では、最大 24 個の Storage VM （ SVM ）がサポートされています。これらの 24 個の Storage VM からデータを提供することも、ディザスタリカバリ（ DR ）用に設定することもできます。
+
Azure では、これまでの上限である DR 用に 12 台の Storage VM を使用しました。





== 書き込みパフォーマンスの向上

このリリースでは、すべてのクラウドプロバイダとすべての構成で、 Cloud Volumes ONTAP の書き込みパフォーマンスが向上しています。



== 新しい EC2 インスタンスタイプがサポートされます

次の Amazon EC2 インスタンスタイプで Cloud Volumes ONTAP がサポートされるようになりました。

* m5a.2xlarge 、 with Standard および BYOL 」の 2 つのタイプがあります
* m5a.16 倍（ Premium および BYOL
* C5a.12xL （プレミアムおよび BYOL ）


の詳細を確認してください https://aws.amazon.com/ec2/instance-types/m5/["M5a インスタンス"^] および https://aws.amazon.com/ec2/instance-types/c5/["C5a インスタンス"^]。

link:reference_configs_aws_990.html["AWS でサポートされている設定を表示します"]。



== Azure で 24 個の Storage VM がサポートされます

独自のライセンスを使用（ BYOL ）すると、 Azure の Cloud Volumes ONTAP で 24 個の Storage VM がサポートされるようになりました。

デフォルトでは、 Cloud Volumes ONTAP に付属する最初の Storage VM 以降に追加する data_serving_storage VM ごとにアドオンライセンスが必要です。アカウントチームに連絡して SVM アドオンライセンスを入手してください。

ディザスタリカバリ（ DR ）用に設定する Storage VM には追加ライセンスは必要ありませんが（無償）、 Storage VM の数は制限に含まれます。

link:reference_limits_azure_990.html#storage-vm-limits["Azure の Storage VM の制限に関する詳細はこちらをご覧ください"]。

https://docs.netapp.com/us-en/occm/task_managing_svms_azure.html["Cloud Volume 用のデータ提供用 Storage VM を作成する方法について説明します Azure の ONTAP"^]。



== 必要な Cloud Manager Connector のバージョン

新しい Cloud Volumes ONTAP 9.9.0 システムを導入し、既存のシステムを 9.9.4.0 にアップグレードするには、 Cloud Manager Connector のバージョン 3.9.4 以降が実行されている必要があります。



== Cloud Manager 3.9.4 で導入された変更点

Cloud Manager 3.9.4 リリースでは、 AWS KMS のサポート強化、 Google Cloud での共有 VPC のサポート、 Google Cloud での IP の削減など、 Cloud Volumes ONTAP の管理機能がいくつか強化されています。

にアクセスします https://docs.netapp.com/us-en/occm/reference_new_occm.html["Cloud Manager リリースノート"^] 3.9.4 リリースの詳細については、を参照してください。



== アップグレードに関する注意事項

* Cloud Volumes ONTAP のアップグレードが Cloud Manager から完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性
* 9.8 リリースから Cloud Volumes ONTAP 9.9.0 にアップグレードできます。既存の Cloud Volumes ONTAP 9.8 システムを 9.9.0 リリースにアップグレードするよう求めるメッセージが Cloud Manager に表示されます。
+
http://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-cloud-volumes-ontap-from-cloud-manager-notifications["Cloud Manager から通知された場合のアップグレード方法について説明します"^]。

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。

