---
sidebar: sidebar 
permalink: reference_new_96.html 
keywords: what's new, new, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.6 には、いくつかの新機能と機能拡張が含まれています 
---
= Cloud Volumes ONTAP 9.6 の新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.6 には、いくつかの新機能と機能拡張が含まれています

その他の機能と機能拡張は、 Cloud Manager の最新バージョンで導入されました。を参照してください https://docs.netapp.com/us-en/occm/reference_new_occm.html["Cloud Manager リリースノート"^] を参照してください。



== 9.6 P8 （ 2020 年 6 月 2 日）

Cloud Volumes ONTAP 9.6 P8 パッチリリースは、 Cloud Manager 3.8 以降で利用できるようになりました。既存のシステムのこのパッチリリースへのアップグレードを求めるプロンプトが Cloud Manager に表示されます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P8["P8 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.6 P7 （ 2020 年 4 月 8 日）

Cloud Volumes ONTAP 9.6 P7 パッチリリースは、 Cloud Manager 3.8 以降で利用できるようになりました。既存のシステムのこのパッチリリースへのアップグレードを求めるプロンプトが Cloud Manager に表示されます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P7["P7 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.6 P6 （ 2020 年 3 月 6 日）

Cloud Volumes ONTAP 9.6 P6 パッチリリースは、 Cloud Manager 3.8 以降で利用できるようになりました。既存のシステムのこのパッチリリースへのアップグレードを求めるプロンプトが Cloud Manager に表示されます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P6["P6 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== AWS の更新プログラム（ 2020 年 2 月 16 日）

新しい EC2 インスタンスのサポートと、サポートされるデータディスク数の変更が導入されました。



=== 新しいインスタンスのサポート

Premium ライセンスまたは BYOL ライセンスを使用する場合、 Cloud Volumes ONTAP 9.6 ではいくつかの新しい EC2 インスタンスタイプがサポートされるようになりました。

* c5.9xlarge のサイズ
* c5d.18 x ラージ ^1,2^
* m5d.8xlarge ^1,2^


^1 このインスタンスタイプには、 Cloud Volumes ONTAP が _Flash Cache _ として使用するローカル NVMe ストレージが含まれています。 https://docs.netapp.com/us-en/occm/concept_flash_cache.html["詳細はこちら。"^]。

^2^ これらのインスタンスタイプは、 9.6 P3 以降でサポートされています。

https://aws.amazon.com/ec2/instance-types/["これらの EC2 インスタンスタイプの詳細については、こちらを参照してください"^]。

link:reference_configs_aws_96.html["AWS でサポートされる 9.6 構成の詳細はこちらをご覧ください"]。



=== サポート対象のデータディスク

C5 、 m5 、および r5 インスタンスで 1 つの少ないデータディスクがサポートされるようになりました。シングルノードシステムの場合は、 22 本のデータディスクがサポートされます。HA ペアの場合、ノードあたり 19 本のデータディスクがサポートされます。

link:reference_limits_aws_96.html["AWS のストレージの制限に関する詳細は、こちらをご覧ください"]。



== Azure での DS15_v2 のサポート（ 2020 年 2 月 12 日）

Cloud Volumes ONTAP が、シングルノードシステムと HA ペアの両方で、 Azure の DS15_v2 仮想マシンタイプでサポートされるようになりました。

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["DSv2 シリーズの詳細については、こちらをご覧ください"^]。

link:reference_configs_azure_96.html["サポートされる 9.6 構成の詳細については、 Azure を参照してください"]。



== 9.6 P5 （ 2019 年 12 月 26 日）

Cloud Volumes ONTAP 用の 9.6 P5 パッチリリースが Cloud Manager から利用できるようになりました。既存のシステムのこのパッチリリースへのアップグレードを求めるプロンプトが Cloud Manager に表示されます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P5["P5 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.6 P4 （ 2019 年 11 月 14 日）

Cloud Volumes ONTAP 9.6 P4 パッチリリースは、 Cloud Manager から入手できるようになりました。既存のシステムのこのパッチリリースへのアップグレードを求めるプロンプトが Cloud Manager に表示されます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P4["P4 パッチで修正されたバグのリストを確認します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.6 P3 （ 2019 年 10 月 23 日）

Cloud Volumes ONTAP 9.6 P3 パッチリリースが Cloud Manager から利用できるようになりました。Cloud Manager から、既存のシステムのこのパッチリリースへのアップグレードを求められます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P3["P3 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。

このリリースでは、バグ修正に加えて、次の機能も有効になっています。

* AWS で c5.18xlarge インスタンスタイプがサポートされます。
* Azure でシングルノードシステムのアグリゲートの最大サイズが拡張されました： 352TB の物理容量がサポートされるようになりました。
+
シングルノードシステムの最大アグリゲートサイズは、これまでは 200TB でした。





== GCP Marketplace での従量課金制サブスクリプション（ 2019 年 10 月 6 日）

Google Cloud Platform Marketplace で Cloud Volumes ONTAP に登録すれば、 Cloud Volumes ONTAP の料金を支払うことができます。

https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?q=NetApp&id=8108721b-10e5-48be-88ed-387031dae492["Google Cloud Platform Marketplace ： Cloud Manager for Cloud Volumes ONTAP"^]



== GCP で Cloud Volumes ONTAP が一般提供されています （ 2019 年 9 月 3 日）

Cloud Volumes ONTAP は、お客様が独自のライセンスを使用（ BYOL ）したときに、一般的に Google Cloud Platform （ GCP ）で利用できるようになりました。従量課金制のプロモーションもご利用いただけます。このキャンペーンでは、無制限のシステム数のライセンスが無料で提供されており、 2019 年 9 月末に有効期限が切れます。

* https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html["GCP の使用を開始する方法をご確認ください"^]
* link:reference_configs_gcp_96.html["サポートされている構成を表示する"]




== 9.6 P2 （ 2019 年 8 月 29 日）

Cloud Volumes ONTAP 9.6 P2 パッチリリースは、 Cloud Manager から入手できます。Cloud Manager から、既存の 9.5 および 9.6 のシステムをこのパッチリリースにアップグレードするように求められます。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P2["P2 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.6 GA （ 2019 年 7 月 15 日）

Cloud Volumes ONTAP 9.6 の General Availability （ GA ）リリースが見積もり可能になりました。GA リリースにはバグの修正が含まれています。既存のシステムをこのリリースにアップグレードするよう求めるプロンプトが Cloud Manager に表示されます。


NOTE: Cloud Volumes ONTAP は、 Google Cloud Platform のプライベートプレビューに残ります。



== 9.6 RC1 （ 2019 年 6 月 16 日）

Cloud Volumes ONTAP 9.6 RC1 は、 AWS 、 Azure 、 Google Cloud Platform で利用できます。このリリースには、次の機能が含まれています。

* <<Private preview of Cloud Volumes ONTAP in Google Cloud Platform>>
* <<Data tiering with HA pairs in Azure>>
* <<Support for FlexCache volumes>>
* <<Additional ONTAP changes>>




=== Google Cloud Platform での Cloud Volumes ONTAP のプライベートプレビュー

Google Cloud Platform の Cloud Volumes ONTAP のプライベートプレビューが利用できるようになりました。他のクラウドプロバイダと同様に、 Cloud Volumes ONTAP for Google Cloud Platform を使用すると、コストの削減、パフォーマンスの向上、可用性の向上を実現できます。

Cloud Volumes ONTAP は、 GCP でシングルノードシステムとして利用でき、オブジェクトストレージへのデータ階層化をサポートします。

プライベートプレビューに参加するには、 ng-Cloud-Volume-ONTAP-preview@netapp.com にリクエストを送信します。



=== Azure の HA ペアによるデータ階層化

データ階層化が Microsoft Azure の Cloud Volumes ONTAP HA ペアでサポートされるようになりました。データ階層化により、使用頻度の低いデータを低コストの BLOB ストレージに自動的に階層化できます。

https://docs.netapp.com/us-en/occm/task_tiering.html["Cloud Manager でデータの階層化を設定する方法について説明します"^]。



=== FlexCache ボリュームのサポート

FlexCache ボリュームは、元の（またはソース）ボリュームから NFS 読み取りデータをキャッシュするストレージボリュームです。その後キャッシュされたデータを読み取ることで、そのデータへのアクセスが高速になります。

FlexCache を使用すると、データアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィック負荷を軽減したりできます。FlexCache ボリュームを使用すると、元のボリュームにアクセスせずに直接データを使用できるため、特にクライアントが同じデータに繰り返しアクセスする場合に、パフォーマンスの向上に役立ちます。FlexCache ボリュームは、読み取り処理が大量に発生するシステムワークロードに適しています。

現時点では、 Cloud Manager で FlexCache ボリュームを管理することはできませんが、 FlexCache CLI または ONTAP System Manager を使用して、 ONTAP ボリュームを作成および管理できます。

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["『 FlexCache Volumes for Faster Data Access Power Guide 』を参照してください"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager での FlexCache ボリュームの作成"^]


3.7.2 リリース以降、 Cloud Manager はすべての新しい Cloud Volumes ONTAP システムに対して FlexCache ライセンスを生成します。ライセンスの使用量は 500GB に制限されています。



=== ONTAP に関するその他の変更点

ONTAP 9.6 には、 Cloud Volumes ONTAP ユーザの関心がある可能性のあるその他の変更が含まれています。

* SnapMirror レプリケーションで、転送中の通信で TLS 1.2 暗号化がサポートされるようになりました
* データ階層化（ FabricPool ）の機能拡張には、次のものがあり
+
** ボリューム移動のサポート。コールドデータを再階層化する必要はありません
** SVM ディザスタリカバリのサポート




9.6 リリースの詳細については、を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリースノート"^]。



== アップグレードに関する注意事項

* Cloud Volumes ONTAP のアップグレードが Cloud Manager から完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性
* Cloud Volumes ONTAP 9.6 には 9.5 リリースからアップグレードできます。
* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。

