---
sidebar: sidebar 
permalink: reference_provider_integrations_990.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support 
summary: このページでは、ネットアップとクラウドプロバイダが連携して発生する可能性のある問題を解決する方法について説明します。 
---
= クラウドプロバイダの統合
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このページでは、ネットアップとクラウドプロバイダが連携して発生する可能性のある問題を解決する方法について説明します。



== 共同サポートのベストプラクティス

ネットアップは、ライセンシーにサポートを提供することを約束し、ライセンシーから報告された場合、 Cloud Volumes ONTAP のテクニカル・サポート問題を解決するために商業的に合理的な努力を払うものとします。ネットアップと該当するクラウドプロバイダは、相互にライセンスを供与されたソフトウェアやインフラに対する直接的なサポート義務を負いません。

ネットアップでは、該当するクラウドプロバイダサービスが原因で発生する可能性のある技術的な問題について、該当するクラウドプロバイダとの連携を目的としたツールを実装しています。ただし、 シームレスなサポートフローを維持する最善の方法は、（ i ）ネットアップと該当するクラウドプロバイダの両方と現在のサポート契約を維持し、（ ii ）技術的な問題が発生した場合には該当するクラウドプロバイダとの共同エスカレーションミーティングを調整することです これらの技術的な問題の原因となっている製品またはサービス。



== Azure メンテナンスイベント

Microsoft では、 Cloud Volumes ONTAP VM に影響する可能性があるメンテナンスイベントのスケジュールを設定し、プログラムによって Azure Virtual Machine （ VM ； Azure 仮想マシン）インフラに対する通知を行います。これらのイベントは、メンテナンス時間の 15 分前に通知されます。

Cloud Volumes ONTAP のハイアベイラビリティ（ HA ）ペアでは、メンテナンスイベントの特別な処理がサポートされます。アプリケーションのヘルスを維持するために、予防的テイクオーバーを実行して安定性を優先させます。 15 秒を超える接続が失われるとフェイルオーバー機能は無効になります。

メンテナンス時間がアナウンスされると、対象のノードのパートナーノードがテイクオーバーを実行します。メンテナンスが完了すると、ギブバックが開始されます。ギブバックが完了すると、 HA ペアは正常な状態に戻ります。この問題が発生しない場合は、ネットアップサポートにお問い合わせください。メンテナンスイベントの対象は、 HA ペアの VM の 1 つです。通常、どちらのノードも比較的短時間です。

Cloud Volumes ONTAP 非継続的可用性を備えた CIFS 共有を使用する CIFS / SMB クライアントでは、テイクオーバーの発生時と、セッションで使用しているアグリゲートがアグリゲートのホームノードにギブバックされたときに、セッションが失われます。これは、 CIFS / SMB プロトコル自体の制限事項です。テイクオーバーやギブバックで発生する可能性のある問題を回避するために、サードパーティ製品の使用が必要になる場合があります。詳しくは、ネットアップサポートにお問い合わせください。
