---
sidebar: sidebar 
permalink: reference_limits_aws_990.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: 信頼性の高い運用を実現するために、 Cloud Volumes ONTAP には AWS にストレージ構成の制限があります。最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。 
---
= AWS での Cloud Volumes ONTAP 9.9.0 のストレージの制限
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、安定した運用を実現するために、ストレージ構成の制限があります最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。



== ライセンス別の最大システム容量

Cloud Volumes ONTAP システムの最大システム容量はライセンスで決まります。最大システム容量には、ディスクベースのストレージに加えて、データの階層化に使用されるオブジェクトストレージが含まれます。ネットアップはこの制限を超えてもサポートしていません。

一部の HA 構成では、ディスク制限により、ディスクのみを使用して 368 TB の容量制限に達することができません。このような場合は、で 368 TB の容量制限に達することができます https://docs.netapp.com/us-en/occm/concept_data_tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。詳細については、以下の容量とディスクの制限を参照してください。

[cols="25,75"]
|===
| 使用許諾 | 最大システム容量（ディスク + オブジェクトストレージ） 


| 調査 | 2TB （ Explore ではデータ階層化はサポートされません） 


| 標準 | 10 TB 


| Premium サービス | 368 TB 


| BYOL | 1 ライセンスあたり 368 TB 
|===


===== HA の場合、ライセンスの容量制限はノード単位か、 HA ペア全体に適用されるか

容量制限は HA ペア全体の容量制限です。ノード単位ではありません。たとえば、 Premium ライセンスを使用する場合、両方のノード間で最大 368 TB の容量を確保できます。



===== AWS の HA システムでは、ミラーリングされたデータは容量制限にカウントされますか。

いいえ、できません。AWS HA ペアのデータは、障害発生時にデータを利用できるように、ノード間で同期的にミラーされます。たとえば、ノード A で 8TB ディスクを購入した場合、 Cloud Manager は、ミラーリングされたデータに使用する 8 TB のディスクをノード B にも割り当てます。16TB の容量がプロビジョニングされましたが、ライセンスの上限には 8TB しかカウントされません。



== ディスクおよび階層化の制限は EC2 インスタンスごとに適用されます

Cloud Volumes ONTAP は EBS ボリュームをディスクとして使用し、最大ディスクサイズは 16TB です。以下のセクションでは、 EC2 インスタンスファミリーごとにディスクと階層化の制限を示します。これは、多くの EC2 インスタンスタイプでディスクの制限が異なるためです。また、シングルノードシステムと HA ペアではディスク制限も異なります。

次の点に注意してください。

* 新しい Cloud Volumes ONTAP 9.9.0 システムでは、 C4 、 M4 、および R4 インスタンスタイプはサポートされません。ただし、これらのインスタンスタイプのいずれかで実行している場合は、システムを 9.9.0 リリースにアップグレードできるため、これらのインスタンスタイプのディスク制限は引き続き表示されます。
* 以下のディスク制限は、ユーザデータが格納されたディスクに固有です。この制限には、ブートディスクとルートディスクは含まれていません。
* Premium ライセンスと BYOL ライセンスでは、容量制限に Explore または Standard ライセンスでアクセスできないため、制限が表示されます。
* Cloud Volumes ONTAP BYOL システムに複数のライセンスを購入して、 368 TB を超える容量を割り当てることができるようになりました。シングルノードシステムまたは HA ペアに対して購入できるライセンスの数に制限はありません。ディスク制限によって、ディスクだけを使用することで容量制限に達することがないことに注意してください。を使用すると、ディスク制限を超えることができます http://docs.netapp.com/occm/us-en/concept_data_tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。 https://docs.netapp.com/us-en/occm/task_managing_licenses.html["Cloud Volume にシステムライセンスを追加する方法について説明します ONTAP"^]。




=== Premium ライセンスがあるシングルノード

[cols="18,18,32,32"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 21 | 336 TB | 368 TB 


| C4 、 M4 、および R4 インスタンス | 34 | 368 TB | 368 TB 
|===


=== 1 つ以上の BYOL ライセンスがあるシングルノード

[cols="18,18,16,16,16,16"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 2+| 最大システム容量（ 1 ライセンス 2+| 複数のライセンスを持つ最大システム容量 


2+|  | * ディスクのみ * | * ディスク + データ階層化 * | * ディスクのみ * | * ディスク + データ階層化 * 


| C5 、 m5 、および r5 インスタンス | 21 | 336 TB | 368 TB | 336 TB | 1 ライセンスあたり 368 TB 


| C4 、 M4 、および R4 インスタンス | 34 | 368 TB | 368 TB | 544 TB | 1 ライセンスあたり 368 TB 
|===


=== Premium ライセンスがある HA ペア

[cols="18,18,32,32"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 18 | 288 TB | 368 TB 


| C4 、 M4 、および R4 インスタンス | 31. | 368 TB | 368 TB 
|===


=== 1 つ以上の BYOL ライセンスがある HA ペア

[cols="18,18,16,16,16,16"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 2+| 最大システム容量（ 1 ライセンス 2+| 複数のライセンスを持つ最大システム容量 


2+|  | * ディスクのみ * | * ディスク + データ階層化 * | * ディスクのみ * | * ディスク + データ階層化 * 


| C5 、 m5 、および r5 インスタンス | 18 | 288 TB | 368 TB | 288 TB | 1 ライセンスあたり 368 TB 


| C4 、 M4 、および R4 インスタンス | 31. | 368 TB | 368 TB | 496 TB | 1 ライセンスあたり 368 TB 
|===


== アグリゲートの制限

Cloud Volumes ONTAP は AWS ボリュームをディスクとして使用し、これらを _Aggregate__ にグループ化します。アグリゲートは、ボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限（ Limit ） 


| アグリゲートの最大数 | 1 つのノード：ディスクリミットの HA ペアと同じです：ノード ^1 の 18 


| 最大アグリゲートサイズ | 96 TB の物理容量 ^2^ 


| アグリゲートあたりのディスク数 | 1-6^3^ 


| アグリゲートあたりの RAID グループの最大数 | 1. 
|===
注：

. HA ペアの両方のノードに 18 個のアグリゲートを作成することはできません。これは、作成するとデータディスクの制限を超えてしまうためです。
. アグリゲートの容量の制限は、アグリゲートを構成するディスクに基づいています。データの階層化に使用されるオブジェクトストレージは制限に含まれません。
. アグリゲート内のディスクはすべて同じサイズである必要があります。




== Storage VM の制限



==== C5 、 M5 、 R5 のインスタンスを使用する BYOL の制限

C5 、 M5 、または R5 のインスタンスタイプを使用する場合、 Cloud Volumes ONTAP BYOL では最大 24 個の Storage VM がサポートされます。ただし、使用する EC2 インスタンスタイプに応じて、上限値を低くすることもできます。インスタンスあたりの制限は、以下のセクションに記載されています。

これら 24 個の Storage VM のうち、ディザスタリカバリ（ DR ）用に最大 12 個を設定できます。

デフォルトでは、 Cloud Volumes ONTAP に付属する最初の Storage VM 以降に追加する data_serving_storage VM ごとにアドオンライセンスが必要です。アカウントチームに問い合わせて Storage VM アドオンライセンスを取得してください。

ディザスタリカバリ（ DR ）用に設定する Storage VM には追加ライセンスは必要ありませんが（無償）、 Storage VM の数は制限に含まれます。たとえば、ディザスタリカバリ用に設定されたデータ提供用の Storage VM が 12 台ある場合、上限に達し、それ以上 Storage VM を作成できません。

https://docs.netapp.com/us-en/occm/task_managing_svms_aws.html["Storage VM を追加で作成する方法について説明します"^]。



==== その他のすべての構成で制限します

PAYGO 構成とその他の BYOL 構成では、いずれも 1 つのデータ提供用 Storage VM と 1 つのデスティネーション Storage VM をディザスタリカバリに使用できます。



==== EC2 インスタンスタイプごとに Storage VM の制限が設定されています

Storage VM を追加で作成する場合は、ポート e0a にプライベート IP アドレスを割り当てる必要があります。次の表に、インターフェイスごとのプライベート IP の最大数と、 Cloud Volumes ONTAP の導入後にポート e0a で使用可能な IP アドレスの数を示します。使用可能な IP アドレスの数は、その構成での Storage VM の最大数に直接影響します。

[cols="6*"]
|===
| 設定 | インスタンスタイプ | インターフェイスあたりのプライベート IP の最大数 | 展開後の IPS の残り時間 ^1 | 管理 LIF がない Storage VM の最大数 ^2 、 3^ | 管理 LIF を使用している Storage VM の最大数 ^2 、 3^ 


.7+| * シングルノード * | *.2xlarge | 15 | 9. | 10. | 5. 


| *.< ：と入力します | 30 | 24 | 24 | 12. 


| * 。 8xlarge | 30 | 24 | 24 | 12. 


| * 。 9xlarge | 30 | 24 | 24 | 12. 


| * 。 12xlarge | 30 | 24 | 24 | 12. 


| *.16 x ラージ | 50 | 44 | 24 | 12. 


| *. 18 倍 | 50 | 44 | 24 | 12. 


.7+| * 単一の AZ* で HA ペア | *.2xlarge | 15 | 10. | 11. | 5. 


| *.< ：と入力します | 30 | 25 | 24 | 12. 


| * 。 8xlarge | 30 | 25 | 24 | 12. 


| * 。 9xlarge | 30 | 25 | 24 | 12. 


| * 。 12xlarge | 30 | 25 | 24 | 12. 


| *.16 x ラージ | 50 | 45 | 24 | 12. 


| *. 18 倍 | 50 | 45 | 24 | 12. 


.7+| * 複数の AZ にまたがる HA ペア * | *.2xlarge | 15 | 12. | 13 | 13 


| *.< ：と入力します | 30 | 27 | 24 | 24 


| * 。 8xlarge | 30 | 27 | 24 | 24 


| * 。 9xlarge | 30 | 27 | 24 | 24 


| * 。 12xlarge | 30 | 27 | 24 | 24 


| *.16 x ラージ | 50 | 47 | 24 | 24 


| *. 18 倍 | 50 | 47 | 24 | 24 
|===
. この数値は、 Cloud Volumes ONTAP の導入とセットアップ後にポート e0a で使用可能な残りのプライベート IP アドレスの数を示します。たとえば、 *.2xlarge システムでは、ネットワークインターフェイスごとに最大 15 の IP アドレスがサポートされます。単一の AZ に HA ペアを導入すると、 5 つのプライベート IP アドレスがポート e0a に割り当てられます。そのため、インスタンスタイプが *.2xlarge の HA ペアでは、追加の Storage VM 用にプライベート IP アドレスが 10 個残っています。
. これらの列に表示される数には、 Cloud Manager がデフォルトで作成する初期 Storage VM が含まれます。たとえば、この列に 24 個表示されている場合、合計 23 個の Storage VM を追加で作成でき、合計 24 個の VM が表示されます。
. Storage VM の管理 LIF はオプションです。管理 LIF は、 SnapCenter などの管理ツールへの接続を提供します。
+
プライベート IP アドレスが必要なため、追加で作成できる Storage VM の数が制限されます。ただし、複数の AZ にまたがる HA ペアは例外です。この場合、管理 LIF の IP アドレスは _floating_ip アドレスであるため、 _private_IP 制限にはカウントされません。





== ファイルとボリュームの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限（ Limit ） 


.2+| * ファイル * | 最大サイズ | 16 TB 


| ボリュームあたりの最大数 | ボリュームサイズは最大 20 億個です 


| * FlexClone ボリューム * | クローン階層の深さ ^1^ | 499 


.3+| * FlexVol ボリューム * | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ | アグリゲートのサイズによって異なります 


| * qtree * | FlexVol あたりの最大数 | 4,995 


| * Snapshot コピー * | FlexVol あたりの最大数 | 1,023 
|===
. クローン階層の深さは、 1 つの FlexVol から作成できる、ネストされた FlexClone ボリュームの最大階層です。




== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSI ストレージ | パラメータ | 制限（ Limit ） 


.4+| * LUN* | ノードあたりの最大数 | 1,024 


| LUN マップの最大数 | 1,024 


| 最大サイズ | 16 TB 


| ボリュームあたりの最大数 | 512 


| * igroup 数 * | ノードあたりの最大数 | 256 


.2+| * イニシエータ * | ノードあたりの最大数 | 512 


| igroup あたりの最大数 | 128 


| * iSCSI セッション * | ノードあたりの最大数 | 1,024 


.2+| * LIF * | ポートあたりの最大数 | 32 


| ポートセットあたりの最大数 | 32 


| * ポートセット * | ノードあたりの最大数 | 256 
|===